repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^birdie_snapshots/.*\.accepted$
      - id: mixed-line-ending
        exclude: ^birdie_snapshots/.*\.accepted$
      - id: trailing-whitespace
        exclude: ^birdie_snapshots/.*\.accepted$
  - repo: https://github.com/jtdowney/pre-commit-gleam
    rev: v1.0.0
    hooks:
      - id: format
      - id: check
